package parsers

import (
	"database/sql"
	"fmt"
	"log"
	"main/models"
	"main/utils"
	"os"
	"time"

	"github.com/joho/godotenv"
	_ "github.com/lib/pq"
)

// ParseDate converts a date string from MM/DD/YY format to a database-friendly YYYY-MM-DD format.
// Returns nil if the date string cannot be parsed.
//
// Parameters:
//   - dateStr: Date string in MM/DD/YY format
//
// Returns:
//   - Date in YYYY-MM-DD format, or nil if parsing fails
func ParseDate(dateStr string) any {
	layout := "01/02/06" // MM/DD/YY format
	parsedTime, err := time.Parse(layout, dateStr)
	if err != nil {
		return nil
	}
	return parsedTime.Format("2006-01-02") // Return YYYY-MM-DD format
}

// ConnectDatabase establishes a connection to the PostgreSQL database using
// credentials from environment variables.
//
// Returns:
//   - A pointer to an sql.DB connection object
func ConnectDatabase() *sql.DB {
	// Load .env file for database credentials
	if err := godotenv.Load(); err != nil {
		log.Fatal("Error loading .env file")
	}

	// Read database connection parameters from environment variables
	username := os.Getenv("DB_USER")
	password := os.Getenv("DB_PASS")
	hostname := os.Getenv("DB_HOST")
	database := os.Getenv("DB_NAME")

	// Build the PostgreSQL connection string
	connectionString := fmt.Sprintf("postgresql://%s:%s@%s/%s?sslmode=disable",
		username, password, hostname, database)

	// Open a connection to the database
	db, err := sql.Open("postgres", connectionString)
	if err != nil {
		log.Fatal("Failed to open database connection:", err)
	}

	// Configure connection pool settings
	db.SetMaxOpenConns(10) // Maximum number of concurrent connections
	db.SetMaxIdleConns(5)  // Maximum number of idle connections to maintain

	// Verify the connection is working
	if err := db.Ping(); err != nil {
		log.Fatal("Failed to connect to database:", err)
	}
	return db
}

// CreateInspectionTable creates the inspections table in the database if it doesn't already exist.
// This table stores data from inspection form PDFs.
//
// Parameters:
//   - db: Database connection
func CreateInspectionTable(db *sql.DB) {
	// SQL query to create the inspections table
	// Note: This creates the table only if it doesn't exist already
	query := `
	CREATE TABLE IF NOT EXISTS inspections (
	id SERIAL PRIMARY KEY,
	pdf_path TEXT UNIQUE,
	bill_to TEXT,
	location TEXT,
	bill_to_ln_2 TEXT,
	location_ln_2 TEXT,
	attention TEXT,
	billing_street TEXT,
	billing_street_ln_2 TEXT,
	location_street TEXT,
	location_street_ln_2 TEXT,
	billing_city_state TEXT,
	billing_city_state_ln_2 TEXT,
	location_city_state TEXT,
	location_city_state_ln_2 TEXT,
	contact TEXT,
	date DATE,
	phone TEXT,
	inspector TEXT,
	email TEXT,
	inspection_frequency TEXT,
	inspection_number TEXT,
	is_the_building_occupied TEXT,
	are_all_systems_in_service TEXT,
	are_fp_systems_same_as_last_inspection TEXT,
	hydraulic_nameplate_securely_attached_and_legible TEXT,
	was_a_main_drain_water_flow_test_conducted TEXT,
	are_all_sprinkler_system_main_control_valves_open TEXT,
	are_all_other_valves_in_proper_position TEXT,
	are_all_control_valves_sealed_or_supervised TEXT,
	are_all_control_valves_in_good_condition_and_free_of_leaks TEXT,
	are_fire_department_connections_in_satisfactory_condition TEXT,
	are_caps_in_place TEXT,
	is_fire_department_connection_easily_accessible TEXT,
	automatic_drain_valve_in_place TEXT,
	is_the_pump_room_heated TEXT,
	is_the_fire_pump_in_service TEXT,
	was_fire_pump_run_during_this_inspection TEXT,
	was_the_pump_started_in_the_automatic_mode_by_a_pressure_drop TEXT,
	were_the_pump_bearings_lubricated TEXT,
	jockey_pump_start_pressure_psi TEXT,
	jockey_pump_start_pressure TEXT,
	jockey_pump_stop_pressure_psi TEXT,
	jockey_pump_stop_pressure TEXT,
	fire_pump_start_pressure_psi TEXT,
	fire_pump_start_pressure TEXT,
	fire_pump_stop_pressure_psi TEXT,
	fire_pump_stop_pressure TEXT,
	is_the_fuel_tank_at_least_2_3_full TEXT,
	is_engine_oil_at_correct_level TEXT,
	is_engine_coolant_at_correct_level TEXT,
	is_the_engine_block_heater_working TEXT,
	is_pump_room_ventilation_operating_properly TEXT,
	was_water_discharge_observed_from_heat_exchanger_return_line TEXT,
	was_cooling_line_strainer_cleaned_after_test TEXT,
	was_pump_run_for_at_least_30_minutes TEXT,
	does_the_switch_in_auto_alarm_work TEXT,
	does_the_pump_running_alarm_work TEXT,
	does_the_common_alarm_work TEXT,
	was_casing_relief_valve_operating_properly TEXT,
	was_pump_run_for_at_least_10_minutes TEXT,
	does_the_loss_of_power_alarm_work TEXT,
	does_the_electric_pump_running_alarm_work TEXT,
	power_failure_condition_simulated_while_pump_operating_at_peak_load TEXT,
	transfer_of_power_to_alternative_power_source_verified TEXT,
	power_failure_condition_removed TEXT,
	pump_reconnected_to_normal_power_source_after_a_time_delay TEXT,
	have_anti_freeze_systems_been_tested TEXT,
	freeze_protection_in_degrees_f TEXT,
	are_alarm_valves_water_flow_devices_and_retards_in_satisfactory_condition TEXT,
	water_flow_alarm_test_conducted_with_inspectors_test TEXT,
	water_flow_alarm_test_conducted_with_bypass_connection TEXT,
	is_dry_valve_in_service_and_in_good_condition TEXT,
	is_dry_valve_itermediate_chamber_not_leaking TEXT,
	has_the_dry_system_been_fully_tripped_within_the_last_three_years TEXT,
	are_quick_opening_device_control_valves_open TEXT,
	is_there_a_list_of_known_low_point_drains_at_the_riser TEXT,
	have_known_low_points_been_drained TEXT,
	is_oil_level_full_on_air_compressor TEXT,
	does_the_air_compressor_return_system_pressure_in_30_minutes_or_under TEXT,
	what_pressure_does_air_compressor_start_psi TEXT,
	what_pressure_does_air_compressor_start TEXT,
	what_pressure_does_air_compressor_stop_psi TEXT,
	what_pressure_does_air_compressor_stop TEXT,
	did_low_air_alarm_operate_psi TEXT,
	did_low_air_alarm_operate TEXT,
	date_of_last_full_trip_test DATE,
	date_of_last_internal_inspection DATE,
	are_valves_in_service_and_in_good_condition TEXT,
	were_valves_tripped TEXT,
	what_pressure_did_pneumatic_actuator_trip_psi TEXT,
	what_pressure_did_pneumatic_actuator_trip TEXT,
	was_priming_line_left_on_after_test TEXT,
	what_pressure_does_preaction_air_compressor_start_psi TEXT,
	what_pressure_does_preaction_air_compressor_start TEXT,
	what_pressure_does_preaction_air_compressor_stop_psi TEXT,
	what_pressure_does_preaction_air_compressor_stop TEXT,
	did_preaction_low_air_alarm_operate_psi TEXT,
	did_preaction_low_air_alarm_operate TEXT,
	does_water_motor_gong_work TEXT,
	does_electric_bell_work TEXT,
	are_water_flow_alarms_operational TEXT,
	are_all_tamper_switches_operational TEXT,
	did_alarm_panel_clear_after_test TEXT,
	are_a_minimum_of_6_spare_sprinklers_readily_avaiable TEXT,
	is_condition_of_piping_and_other_system_componets_satisfactory TEXT,
	are_known_dry_type_heads_less_than_10_years_old TEXT,
	are_known_dry_type_heads_less_than_10_years_old_year TEXT,
	are_known_quick_response_heads_less_than_20_years_old TEXT,
	are_known_quick_response_heads_less_than_20_years_old_year TEXT,
	are_known_standard_response_heads_less_than_50_years_old TEXT,
	are_known_standard_response_heads_less_than_50_years_old_year TEXT,
	have_all_gauges_been_tested_or_replaced_in_the_last_5_years TEXT,
	have_all_gauges_been_tested_or_replaced_in_the_last_5_years_year TEXT,
	system_1_name TEXT,
	system_1_drain_size TEXT,
	system_1_static_psi TEXT,
	system_1_residual_psi TEXT,
	system_2_name TEXT,
	system_2_drain_size TEXT,
	system_2_static_psi TEXT,
	system_2_residual_psi TEXT,
	system_3_name TEXT,
	system_3_drain_size TEXT,
	system_3_static_psi TEXT,
	system_3_residual_psi TEXT,
	system_4_name TEXT,
	system_4_drain_size TEXT,
	system_4_static_psi TEXT,
	system_4_residual_psi TEXT,
	system_5_name TEXT,
	system_5_drain_size TEXT,
	system_5_static_psi TEXT,
	system_5_residual_psi TEXT,
	system_6_name TEXT,
	system_6_drain_size TEXT,
	system_6_static_psi TEXT,
	system_6_residual_psi TEXT,
	drain_test_notes TEXT,
	device_1_name TEXT,
	device_1_address TEXT,
	device_1_description_location TEXT,
	device_1_operated TEXT,
	device_1_delay_sec TEXT,
	device_2_name TEXT,
	device_2_address TEXT,
	device_2_description_location TEXT,
	device_2_operated TEXT,
	device_2_delay_sec TEXT,
	device_3_name TEXT,
	device_3_address TEXT,
	device_3_description_location TEXT,
	device_3_operated TEXT,
	device_3_delay_sec TEXT,
	device_4_name TEXT,
	device_4_address TEXT,
	device_4_description_location TEXT,
	device_4_operated TEXT,
	device_4_delay_sec TEXT,
	device_5_name TEXT,
	device_5_address TEXT,
	device_5_description_location TEXT,
	device_5_operated TEXT,
	device_5_delay_sec TEXT,
	device_6_name TEXT,
	device_6_address TEXT,
	device_6_description_location TEXT,
	device_6_operated TEXT,
	device_6_delay_sec TEXT,
	device_7_name TEXT,
	device_7_address TEXT,
	device_7_description_location TEXT,
	device_7_operated TEXT,
	device_7_delay_sec TEXT,
	device_8_name TEXT,
	device_8_address TEXT,
	device_8_description_location TEXT,
	device_8_operated TEXT,
	device_8_delay_sec TEXT,
	device_9_name TEXT,
	device_9_address TEXT,
	device_9_description_location TEXT,
	device_9_operated TEXT,
	device_9_delay_sec TEXT,
	device_10_name TEXT,
	device_10_address TEXT,
	device_10_description_location TEXT,
	device_10_operated TEXT,
	device_10_delay_sec TEXT,
	device_11_name TEXT,
	device_11_address TEXT,
	device_11_description_location TEXT,
	device_11_operated TEXT,
	device_11_delay_sec TEXT,
	device_12_name TEXT,
	device_12_address TEXT,
	device_12_description_location TEXT,
	device_12_operated TEXT,
	device_12_delay_sec TEXT,
	device_13_name TEXT,
	device_13_address TEXT,
	device_13_description_location TEXT,
	device_13_operated TEXT,
	device_13_delay_sec TEXT,
	device_14_name TEXT,
	device_14_address TEXT,
	device_14_description_location TEXT,
	device_14_operated TEXT,
	device_14_delay_sec TEXT,
	adjustments_or_corrections_make TEXT,
	explanation_of_any_no_answers TEXT,
	explanation_of_any_no_answers_continued TEXT,
	notes TEXT
	)`
	_, err := db.Exec(query)
	if err != nil {
		utils.LogSafe("Could not create the Inspection Table: %+v", err)
	}
}

func InsertInspectionTable(db *sql.DB, form models.InspectionForm) {
	query := `
	INSERT INTO inspections (
	pdf_path,
	bill_to,
	location,
	bill_to_ln_2,
	location_ln_2,
	attention,
	billing_street,
	billing_street_ln_2,
	location_street,
	location_street_ln_2,
	billing_city_state,
	billing_city_state_ln_2,
	location_city_state,
	location_city_state_ln_2,
	contact,
	date,
	phone,
	inspector,
	email,
	inspection_frequency,
	inspection_number,
	is_the_building_occupied,
	are_all_systems_in_service,
	are_fp_systems_same_as_last_inspection,
	hydraulic_nameplate_securely_attached_and_legible,
	was_a_main_drain_water_flow_test_conducted,
	are_all_sprinkler_system_main_control_valves_open,
	are_all_other_valves_in_proper_position,
	are_all_control_valves_sealed_or_supervised,
	are_all_control_valves_in_good_condition_and_free_of_leaks,
	are_fire_department_connections_in_satisfactory_condition,
	are_caps_in_place,
	is_fire_department_connection_easily_accessible,
	automatic_drain_valve_in_place,
	is_the_pump_room_heated,
	is_the_fire_pump_in_service,
	was_fire_pump_run_during_this_inspection,
	was_the_pump_started_in_the_automatic_mode_by_a_pressure_drop,
	were_the_pump_bearings_lubricated,
	jockey_pump_start_pressure_psi,
	jockey_pump_start_pressure,
	jockey_pump_stop_pressure_psi,
	jockey_pump_stop_pressure,
	fire_pump_start_pressure_psi,
	fire_pump_start_pressure,
	fire_pump_stop_pressure_psi,
	fire_pump_stop_pressure,
	is_the_fuel_tank_at_least_2_3_full,
	is_engine_oil_at_correct_level,
	is_engine_coolant_at_correct_level,
	is_the_engine_block_heater_working,
	is_pump_room_ventilation_operating_properly,
	was_water_discharge_observed_from_heat_exchanger_return_line,
	was_cooling_line_strainer_cleaned_after_test,
	was_pump_run_for_at_least_30_minutes,
	does_the_switch_in_auto_alarm_work,
	does_the_pump_running_alarm_work,
	does_the_common_alarm_work,
	was_casing_relief_valve_operating_properly,
	was_pump_run_for_at_least_10_minutes,
	does_the_loss_of_power_alarm_work,
	does_the_electric_pump_running_alarm_work,
	power_failure_condition_simulated_while_pump_operating_at_peak_load,
	transfer_of_power_to_alternative_power_source_verified,
	power_failure_condition_removed,
	pump_reconnected_to_normal_power_source_after_a_time_delay,
	have_anti_freeze_systems_been_tested,
	freeze_protection_in_degrees_f,
	are_alarm_valves_water_flow_devices_and_retards_in_satisfactory_condition,
	water_flow_alarm_test_conducted_with_inspectors_test,
	water_flow_alarm_test_conducted_with_bypass_connection,
	is_dry_valve_in_service_and_in_good_condition,
	is_dry_valve_itermediate_chamber_not_leaking,
	has_the_dry_system_been_fully_tripped_within_the_last_three_years,
	are_quick_opening_device_control_valves_open,
	is_there_a_list_of_known_low_point_drains_at_the_riser,
	have_known_low_points_been_drained,
	is_oil_level_full_on_air_compressor,
	does_the_air_compressor_return_system_pressure_in_30_minutes_or_under,
	what_pressure_does_air_compressor_start_psi,
	what_pressure_does_air_compressor_start,
	what_pressure_does_air_compressor_stop_psi,
	what_pressure_does_air_compressor_stop,
	did_low_air_alarm_operate_psi,
	did_low_air_alarm_operate,
	date_of_last_full_trip_test,
	date_of_last_internal_inspection,
	are_valves_in_service_and_in_good_condition,
	were_valves_tripped,
	what_pressure_did_pneumatic_actuator_trip_psi,
	what_pressure_did_pneumatic_actuator_trip,
	was_priming_line_left_on_after_test,
	what_pressure_does_preaction_air_compressor_start_psi,
	what_pressure_does_preaction_air_compressor_start,
	what_pressure_does_preaction_air_compressor_stop_psi,
	what_pressure_does_preaction_air_compressor_stop,
	did_preaction_low_air_alarm_operate_psi,
	did_preaction_low_air_alarm_operate,
	does_water_motor_gong_work,
	does_electric_bell_work,
	are_water_flow_alarms_operational,
	are_all_tamper_switches_operational,
	did_alarm_panel_clear_after_test,
	are_a_minimum_of_6_spare_sprinklers_readily_avaiable,
	is_condition_of_piping_and_other_system_componets_satisfactory,
	are_known_dry_type_heads_less_than_10_years_old,
	are_known_dry_type_heads_less_than_10_years_old_year,
	are_known_quick_response_heads_less_than_20_years_old,
	are_known_quick_response_heads_less_than_20_years_old_year,
	are_known_standard_response_heads_less_than_50_years_old,
	are_known_standard_response_heads_less_than_50_years_old_year,
	have_all_gauges_been_tested_or_replaced_in_the_last_5_years,
	have_all_gauges_been_tested_or_replaced_in_the_last_5_years_year,
	system_1_name,
	system_1_drain_size,
	system_1_static_psi,
	system_1_residual_psi,
	system_2_name,
	system_2_drain_size,
	system_2_static_psi,
	system_2_residual_psi,
	system_3_name,
	system_3_drain_size,
	system_3_static_psi,
	system_3_residual_psi,
	system_4_name,
	system_4_drain_size,
	system_4_static_psi,
	system_4_residual_psi,
	system_5_name,
	system_5_drain_size,
	system_5_static_psi,
	system_5_residual_psi,
	system_6_name,
	system_6_drain_size,
	system_6_static_psi,
	system_6_residual_psi,
	drain_test_notes,
	device_1_name,
	device_1_address,
	device_1_description_location,
	device_1_operated,
	device_1_delay_sec,
	device_2_name,
	device_2_address,
	device_2_description_location,
	device_2_operated,
	device_2_delay_sec,
	device_3_name,
	device_3_address,
	device_3_description_location,
	device_3_operated,
	device_3_delay_sec,
	device_4_name,
	device_4_address,
	device_4_description_location,
	device_4_operated,
	device_4_delay_sec,
	device_5_name,
	device_5_address,
	device_5_description_location,
	device_5_operated,
	device_5_delay_sec,
	device_6_name,
	device_6_address,
	device_6_description_location,
	device_6_operated,
	device_6_delay_sec,
	device_7_name,
	device_7_address,
	device_7_description_location,
	device_7_operated,
	device_7_delay_sec,
	device_8_name,
	device_8_address,
	device_8_description_location,
	device_8_operated,
	device_8_delay_sec,
	device_9_name,
	device_9_address,
	device_9_description_location,
	device_9_operated,
	device_9_delay_sec,
	device_10_name,
	device_10_address,
	device_10_description_location,
	device_10_operated,
	device_10_delay_sec,
	device_11_name,
	device_11_address,
	device_11_description_location,
	device_11_operated,
	device_11_delay_sec,
	device_12_name,
	device_12_address,
	device_12_description_location,
	device_12_operated,
	device_12_delay_sec,
	device_13_name,
	device_13_address,
	device_13_description_location,
	device_13_operated,
	device_13_delay_sec,
	device_14_name,
	device_14_address,
	device_14_description_location,
	device_14_operated,
	device_14_delay_sec,
	adjustments_or_corrections_make,
	explanation_of_any_no_answers,
	explanation_of_any_no_answers_continued,
	notes
	) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9,
	$10,
	$11,
	$12,
	$13,
	$14,
	$15,
	$16,
	$17,
	$18,
	$19,
	$20,
	$21,
	$22,
	$23,
	$24,
	$25,
	$26,
	$27,
	$28,
	$29,
	$30,
	$31,
	$32,
	$33,
	$34,
	$35,
	$36,
	$37,
	$38,
	$39,
	$40,
	$41,
	$42,
	$43,
	$44,
	$45,
	$46,
	$47,
	$48,
	$49,
	$50,
	$51,
	$52,
	$53,
	$54,
	$55,
	$56,
	$57,
	$58,
	$59,
	$60,
	$61,
	$62,
	$63,
	$64,
	$65,
	$66,
	$67,
	$68,
	$69,
	$70,
	$71,
	$72,
	$73,
	$74,
	$75,
	$76,
	$77,
	$78,
	$79,
	$80,
	$81,
	$82,
	$83,
	$84,
	$85,
	$86,
	$87,
	$88,
	$89,
	$90,
	$91,
	$92,
	$93,
	$94,
	$95,
	$96,
	$97,
	$98,
	$99,
	$100,
	$101,
	$102,
	$103,
	$104,
	$105,
	$106,
	$107,
	$108,
	$109,
	$110,
	$111,
	$112,
	$113,
	$114,
	$115,
	$116,
	$117,
	$118,
	$119,
	$120,
	$121,
	$122,
	$123,
	$124,
	$125,
	$126,
	$127,
	$128,
	$129,
	$130,
	$131,
	$132,
	$133,
	$134,
	$135,
	$136,
	$137,
	$138,
	$139,
	$140,
	$141,
	$142,
	$143,
	$144,
	$145,
	$146,
	$147,
	$148,
	$149,
	$150,
	$151,
	$152,
	$153,
	$154,
	$155,
	$156,
	$157,
	$158,
	$159,
	$160,
	$161,
	$162,
	$163,
	$164,
	$165,
	$166,
	$167,
	$168,
	$169,
	$170,
	$171,
	$172,
	$173,
	$174,
	$175,
	$176,
	$177,
	$178,
	$179,
	$180,
	$181,
	$182,
	$183,
	$184,
	$185,
	$186,
	$187,
	$188,
	$189,
	$190,
	$191,
	$192,
	$193,
	$194,
	$195,
	$196,
	$197,
	$198,
	$199,
	$200,
	$201,
	$202,
	$203,
	$204,
	$205,
	$206,
	$207,
	$208,
	$209,
	$210,
	$211,
	$212
	) ON CONFLICT (pdf_path) DO UPDATE SET
	bill_to = EXCLUDED.bill_to,
	location = EXCLUDED.location,
	bill_to_ln_2 = EXCLUDED.bill_to_ln_2,
	location_ln_2 = EXCLUDED.location_ln_2,
	attention = EXCLUDED.attention,
	billing_street = EXCLUDED.billing_street,
	billing_street_ln_2 = EXCLUDED.billing_street_ln_2,
	location_street = EXCLUDED.location_street,
	location_street_ln_2 = EXCLUDED.location_street_ln_2,
	billing_city_state = EXCLUDED.billing_city_state,
	billing_city_state_ln_2 = EXCLUDED.billing_city_state_ln_2,
	location_city_state = EXCLUDED.location_city_state,
	location_city_state_ln_2 = EXCLUDED.location_city_state_ln_2,
	contact = EXCLUDED.contact,
	date = EXCLUDED.date,
	phone = EXCLUDED.phone,
	inspector = EXCLUDED.inspector,
	email = EXCLUDED.email,
	inspection_frequency = EXCLUDED.inspection_frequency,
	inspection_number = EXCLUDED.inspection_number,
	is_the_building_occupied = EXCLUDED.is_the_building_occupied,
	are_all_systems_in_service = EXCLUDED.are_all_systems_in_service,
	are_fp_systems_same_as_last_inspection = EXCLUDED.are_fp_systems_same_as_last_inspection,
	hydraulic_nameplate_securely_attached_and_legible = EXCLUDED.hydraulic_nameplate_securely_attached_and_legible,
	was_a_main_drain_water_flow_test_conducted = EXCLUDED.was_a_main_drain_water_flow_test_conducted,
	are_all_sprinkler_system_main_control_valves_open = EXCLUDED.are_all_sprinkler_system_main_control_valves_open,
	are_all_other_valves_in_proper_position = EXCLUDED.are_all_other_valves_in_proper_position,
	are_all_control_valves_sealed_or_supervised = EXCLUDED.are_all_control_valves_sealed_or_supervised,
	are_all_control_valves_in_good_condition_and_free_of_leaks = EXCLUDED.are_all_control_valves_in_good_condition_and_free_of_leaks,
	are_fire_department_connections_in_satisfactory_condition = EXCLUDED.are_fire_department_connections_in_satisfactory_condition,
	are_caps_in_place = EXCLUDED.are_caps_in_place,
	is_fire_department_connection_easily_accessible = EXCLUDED.is_fire_department_connection_easily_accessible,
	automatic_drain_valve_in_place = EXCLUDED.automatic_drain_valve_in_place,
	is_the_pump_room_heated = EXCLUDED.is_the_pump_room_heated,
	is_the_fire_pump_in_service = EXCLUDED.is_the_fire_pump_in_service,
	was_fire_pump_run_during_this_inspection = EXCLUDED.was_fire_pump_run_during_this_inspection,
	was_the_pump_started_in_the_automatic_mode_by_a_pressure_drop = EXCLUDED.was_the_pump_started_in_the_automatic_mode_by_a_pressure_drop,
	were_the_pump_bearings_lubricated = EXCLUDED.were_the_pump_bearings_lubricated,
	jockey_pump_start_pressure_psi = EXCLUDED.jockey_pump_start_pressure_psi,
	jockey_pump_start_pressure = EXCLUDED.jockey_pump_start_pressure,
	jockey_pump_stop_pressure_psi = EXCLUDED.jockey_pump_stop_pressure_psi,
	jockey_pump_stop_pressure = EXCLUDED.jockey_pump_stop_pressure,
	fire_pump_start_pressure_psi = EXCLUDED.fire_pump_start_pressure_psi,
	fire_pump_start_pressure = EXCLUDED.fire_pump_start_pressure,
	fire_pump_stop_pressure_psi = EXCLUDED.fire_pump_stop_pressure_psi,
	fire_pump_stop_pressure = EXCLUDED.fire_pump_stop_pressure,
	is_the_fuel_tank_at_least_2_3_full = EXCLUDED.is_the_fuel_tank_at_least_2_3_full,
	is_engine_oil_at_correct_level = EXCLUDED.is_engine_oil_at_correct_level,
	is_engine_coolant_at_correct_level = EXCLUDED.is_engine_coolant_at_correct_level,
	is_the_engine_block_heater_working = EXCLUDED.is_the_engine_block_heater_working,
	is_pump_room_ventilation_operating_properly = EXCLUDED.is_pump_room_ventilation_operating_properly,
	was_water_discharge_observed_from_heat_exchanger_return_line = EXCLUDED.was_water_discharge_observed_from_heat_exchanger_return_line,
	was_cooling_line_strainer_cleaned_after_test = EXCLUDED.was_cooling_line_strainer_cleaned_after_test,
	was_pump_run_for_at_least_30_minutes = EXCLUDED.was_pump_run_for_at_least_30_minutes,
	does_the_switch_in_auto_alarm_work = EXCLUDED.does_the_switch_in_auto_alarm_work,
	does_the_pump_running_alarm_work = EXCLUDED.does_the_pump_running_alarm_work,
	does_the_common_alarm_work = EXCLUDED.does_the_common_alarm_work,
	was_casing_relief_valve_operating_properly = EXCLUDED.was_casing_relief_valve_operating_properly,
	was_pump_run_for_at_least_10_minutes = EXCLUDED.was_pump_run_for_at_least_10_minutes,
	does_the_loss_of_power_alarm_work = EXCLUDED.does_the_loss_of_power_alarm_work,
	does_the_electric_pump_running_alarm_work = EXCLUDED.does_the_electric_pump_running_alarm_work,
	power_failure_condition_simulated_while_pump_operating_at_peak_load = EXCLUDED.power_failure_condition_simulated_while_pump_operating_at_peak_load,
	transfer_of_power_to_alternative_power_source_verified = EXCLUDED.transfer_of_power_to_alternative_power_source_verified,
	power_failure_condition_removed = EXCLUDED.power_failure_condition_removed,
	pump_reconnected_to_normal_power_source_after_a_time_delay = EXCLUDED.pump_reconnected_to_normal_power_source_after_a_time_delay,
	have_anti_freeze_systems_been_tested = EXCLUDED.have_anti_freeze_systems_been_tested,
	freeze_protection_in_degrees_f = EXCLUDED.freeze_protection_in_degrees_f,
	are_alarm_valves_water_flow_devices_and_retards_in_satisfactory_condition = EXCLUDED.are_alarm_valves_water_flow_devices_and_retards_in_satisfactory_condition,
	water_flow_alarm_test_conducted_with_inspectors_test = EXCLUDED.water_flow_alarm_test_conducted_with_inspectors_test,
	water_flow_alarm_test_conducted_with_bypass_connection = EXCLUDED.water_flow_alarm_test_conducted_with_bypass_connection,
	is_dry_valve_in_service_and_in_good_condition = EXCLUDED.is_dry_valve_in_service_and_in_good_condition,
	is_dry_valve_itermediate_chamber_not_leaking = EXCLUDED.is_dry_valve_itermediate_chamber_not_leaking,
	has_the_dry_system_been_fully_tripped_within_the_last_three_years = EXCLUDED.has_the_dry_system_been_fully_tripped_within_the_last_three_years,
	are_quick_opening_device_control_valves_open = EXCLUDED.are_quick_opening_device_control_valves_open,
	is_there_a_list_of_known_low_point_drains_at_the_riser = EXCLUDED.is_there_a_list_of_known_low_point_drains_at_the_riser,
	have_known_low_points_been_drained = EXCLUDED.have_known_low_points_been_drained,
	is_oil_level_full_on_air_compressor = EXCLUDED.is_oil_level_full_on_air_compressor,
	does_the_air_compressor_return_system_pressure_in_30_minutes_or_under = EXCLUDED.does_the_air_compressor_return_system_pressure_in_30_minutes_or_under,
	what_pressure_does_air_compressor_start_psi = EXCLUDED.what_pressure_does_air_compressor_start_psi,
	what_pressure_does_air_compressor_start = EXCLUDED.what_pressure_does_air_compressor_start,
	what_pressure_does_air_compressor_stop_psi = EXCLUDED.what_pressure_does_air_compressor_stop_psi,
	what_pressure_does_air_compressor_stop = EXCLUDED.what_pressure_does_air_compressor_stop,
	did_low_air_alarm_operate_psi = EXCLUDED.did_low_air_alarm_operate_psi,
	did_low_air_alarm_operate = EXCLUDED.did_low_air_alarm_operate,
	date_of_last_full_trip_test = EXCLUDED.date_of_last_full_trip_test,
	date_of_last_internal_inspection = EXCLUDED.date_of_last_internal_inspection,
	are_valves_in_service_and_in_good_condition = EXCLUDED.are_valves_in_service_and_in_good_condition,
	were_valves_tripped = EXCLUDED.were_valves_tripped,
	what_pressure_did_pneumatic_actuator_trip_psi = EXCLUDED.what_pressure_did_pneumatic_actuator_trip_psi,
	what_pressure_did_pneumatic_actuator_trip = EXCLUDED.what_pressure_did_pneumatic_actuator_trip,
	was_priming_line_left_on_after_test = EXCLUDED.was_priming_line_left_on_after_test,
	what_pressure_does_preaction_air_compressor_start_psi = EXCLUDED.what_pressure_does_preaction_air_compressor_start_psi,
	what_pressure_does_preaction_air_compressor_start = EXCLUDED.what_pressure_does_preaction_air_compressor_start,
	what_pressure_does_preaction_air_compressor_stop_psi = EXCLUDED.what_pressure_does_preaction_air_compressor_stop_psi,
	what_pressure_does_preaction_air_compressor_stop = EXCLUDED.what_pressure_does_preaction_air_compressor_stop,
	did_preaction_low_air_alarm_operate_psi = EXCLUDED.did_preaction_low_air_alarm_operate_psi,
	did_preaction_low_air_alarm_operate = EXCLUDED.did_preaction_low_air_alarm_operate,
	does_water_motor_gong_work = EXCLUDED.does_water_motor_gong_work,
	does_electric_bell_work = EXCLUDED.does_electric_bell_work,
	are_water_flow_alarms_operational = EXCLUDED.are_water_flow_alarms_operational,
	are_all_tamper_switches_operational = EXCLUDED.are_all_tamper_switches_operational,
	did_alarm_panel_clear_after_test = EXCLUDED.did_alarm_panel_clear_after_test,
	are_a_minimum_of_6_spare_sprinklers_readily_avaiable = EXCLUDED.are_a_minimum_of_6_spare_sprinklers_readily_avaiable,
	is_condition_of_piping_and_other_system_componets_satisfactory = EXCLUDED.is_condition_of_piping_and_other_system_componets_satisfactory,
	are_known_dry_type_heads_less_than_10_years_old = EXCLUDED.are_known_dry_type_heads_less_than_10_years_old,
	are_known_dry_type_heads_less_than_10_years_old_year = EXCLUDED.are_known_dry_type_heads_less_than_10_years_old_year,
	are_known_quick_response_heads_less_than_20_years_old = EXCLUDED.are_known_quick_response_heads_less_than_20_years_old,
	are_known_quick_response_heads_less_than_20_years_old_year = EXCLUDED.are_known_quick_response_heads_less_than_20_years_old_year,
	are_known_standard_response_heads_less_than_50_years_old = EXCLUDED.are_known_standard_response_heads_less_than_50_years_old,
	are_known_standard_response_heads_less_than_50_years_old_year = EXCLUDED.are_known_standard_response_heads_less_than_50_years_old_year,
	have_all_gauges_been_tested_or_replaced_in_the_last_5_years = EXCLUDED.have_all_gauges_been_tested_or_replaced_in_the_last_5_years,
	have_all_gauges_been_tested_or_replaced_in_the_last_5_years_year = EXCLUDED.have_all_gauges_been_tested_or_replaced_in_the_last_5_years_year,
	system_1_name = EXCLUDED.system_1_name,
	system_1_drain_size = EXCLUDED.system_1_drain_size,
	system_1_static_psi = EXCLUDED.system_1_static_psi,
	system_1_residual_psi = EXCLUDED.system_1_residual_psi,
	system_2_name = EXCLUDED.system_2_name,
	system_2_drain_size = EXCLUDED.system_2_drain_size,
	system_2_static_psi = EXCLUDED.system_2_static_psi,
	system_2_residual_psi = EXCLUDED.system_2_residual_psi,
	system_3_name = EXCLUDED.system_3_name,
	system_3_drain_size = EXCLUDED.system_3_drain_size,
	system_3_static_psi = EXCLUDED.system_3_static_psi,
	system_3_residual_psi = EXCLUDED.system_3_residual_psi,
	system_4_name = EXCLUDED.system_4_name,
	system_4_drain_size = EXCLUDED.system_4_drain_size,
	system_4_static_psi = EXCLUDED.system_4_static_psi,
	system_4_residual_psi = EXCLUDED.system_4_residual_psi,
	system_5_name = EXCLUDED.system_5_name,
	system_5_drain_size = EXCLUDED.system_5_drain_size,
	system_5_static_psi = EXCLUDED.system_5_static_psi,
	system_5_residual_psi = EXCLUDED.system_5_residual_psi,
	system_6_name = EXCLUDED.system_6_name,
	system_6_drain_size = EXCLUDED.system_6_drain_size,
	system_6_static_psi = EXCLUDED.system_6_static_psi,
	system_6_residual_psi = EXCLUDED.system_6_residual_psi,
	drain_test_notes = EXCLUDED.drain_test_notes,
	device_1_name = EXCLUDED.device_1_name,
	device_1_address = EXCLUDED.device_1_address,
	device_1_description_location = EXCLUDED.device_1_description_location,
	device_1_operated = EXCLUDED.device_1_operated,
	device_1_delay_sec = EXCLUDED.device_1_delay_sec,
	device_2_name = EXCLUDED.device_2_name,
	device_2_address = EXCLUDED.device_2_address,
	device_2_description_location = EXCLUDED.device_2_description_location,
	device_2_operated = EXCLUDED.device_2_operated,
	device_2_delay_sec = EXCLUDED.device_2_delay_sec,
	device_3_name = EXCLUDED.device_3_name,
	device_3_address = EXCLUDED.device_3_address,
	device_3_description_location = EXCLUDED.device_3_description_location,
	device_3_operated = EXCLUDED.device_3_operated,
	device_3_delay_sec = EXCLUDED.device_3_delay_sec,
	device_4_name = EXCLUDED.device_4_name,
	device_4_address = EXCLUDED.device_4_address,
	device_4_description_location = EXCLUDED.device_4_description_location,
	device_4_operated = EXCLUDED.device_4_operated,
	device_4_delay_sec = EXCLUDED.device_4_delay_sec,
	device_5_name = EXCLUDED.device_5_name,
	device_5_address = EXCLUDED.device_5_address,
	device_5_description_location = EXCLUDED.device_5_description_location,
	device_5_operated = EXCLUDED.device_5_operated,
	device_5_delay_sec = EXCLUDED.device_5_delay_sec,
	device_6_name = EXCLUDED.device_6_name,
	device_6_address = EXCLUDED.device_6_address,
	device_6_description_location = EXCLUDED.device_6_description_location,
	device_6_operated = EXCLUDED.device_6_operated,
	device_6_delay_sec = EXCLUDED.device_6_delay_sec,
	device_7_name = EXCLUDED.device_7_name,
	device_7_address = EXCLUDED.device_7_address,
	device_7_description_location = EXCLUDED.device_7_description_location,
	device_7_operated = EXCLUDED.device_7_operated,
	device_7_delay_sec = EXCLUDED.device_7_delay_sec,
	device_8_name = EXCLUDED.device_8_name,
	device_8_address = EXCLUDED.device_8_address,
	device_8_description_location = EXCLUDED.device_8_description_location,
	device_8_operated = EXCLUDED.device_8_operated,
	device_8_delay_sec = EXCLUDED.device_8_delay_sec,
	device_9_name = EXCLUDED.device_9_name,
	device_9_address = EXCLUDED.device_9_address,
	device_9_description_location = EXCLUDED.device_9_description_location,
	device_9_operated = EXCLUDED.device_9_operated,
	device_9_delay_sec = EXCLUDED.device_9_delay_sec,
	device_10_name = EXCLUDED.device_10_name,
	device_10_address = EXCLUDED.device_10_address,
	device_10_description_location = EXCLUDED.device_10_description_location,
	device_10_operated = EXCLUDED.device_10_operated,
	device_10_delay_sec = EXCLUDED.device_10_delay_sec,
	device_11_name = EXCLUDED.device_11_name,
	device_11_address = EXCLUDED.device_11_address,
	device_11_description_location = EXCLUDED.device_11_description_location,
	device_11_operated = EXCLUDED.device_11_operated,
	device_11_delay_sec = EXCLUDED.device_11_delay_sec,
	device_12_name = EXCLUDED.device_12_name,
	device_12_address = EXCLUDED.device_12_address,
	device_12_description_location = EXCLUDED.device_12_description_location,
	device_12_operated = EXCLUDED.device_12_operated,
	device_12_delay_sec = EXCLUDED.device_12_delay_sec,
	device_13_name = EXCLUDED.device_13_name,
	device_13_address = EXCLUDED.device_13_address,
	device_13_description_location = EXCLUDED.device_13_description_location,
	device_13_operated = EXCLUDED.device_13_operated,
	device_13_delay_sec = EXCLUDED.device_13_delay_sec,
	device_14_name = EXCLUDED.device_14_name,
	device_14_address = EXCLUDED.device_14_address,
	device_14_description_location = EXCLUDED.device_14_description_location,
	device_14_operated = EXCLUDED.device_14_operated,
	device_14_delay_sec = EXCLUDED.device_14_delay_sec,
	adjustments_or_corrections_make = EXCLUDED.adjustments_or_corrections_make,
	explanation_of_any_no_answers = EXCLUDED.explanation_of_any_no_answers,
	explanation_of_any_no_answers_continued = EXCLUDED.explanation_of_any_no_answers_continued,
	notes = EXCLUDED.notes`
	_, err := db.Exec(query,
		form.PDF_Path,
		form.Bill_To,
		form.Location,
		form.Bill_To_LN_2,
		form.Location_LN_2,
		form.Attention,
		form.Billing_Street,
		form.Billing_Street_LN_2,
		form.Location_Street,
		form.Location_Street_LN_2,
		form.Billing_City_State,
		form.Billing_City_State_LN_2,
		form.Location_City_State,
		form.Location_City_State_LN_2,
		form.Contact,
		ParseDate(form.Date),
		form.Phone,
		form.Inspector,
		form.Email,
		form.Inspection_Frequency,
		form.Inspection_Number,
		form.Is_The_Building_Occupied,
		form.Are_All_Systems_In_Service,
		form.Are_FP_Systems_Same_as_Last_Inspection,
		form.Hydraulic_Nameplate_Securely_Attached_And_Legible,
		form.Was_A_Main_Drain_Water_Flow_Test_Conducted,
		form.Are_All_Sprinkler_System_Main_Control_Valves_Open,
		form.Are_All_Other_Valves_In_Proper_Position,
		form.Are_All_Control_Valves_Sealed_Or_Supervised,
		form.Are_All_Control_Valves_In_Good_Condition_and_Free_Of_Leaks,
		form.Are_Fire_Department_Connections_In_Satisfactory_Condition,
		form.Are_Caps_In_Place,
		form.Is_Fire_Department_Connection_Easily_Accessible,
		form.Automatic_Drain_Vale_In_Place,
		form.Is_The_Pump_Room_Heated,
		form.Is_The_Fire_Pump_In_Service,
		form.Was_Fire_Pump_Run_During_This_Inspection,
		form.Was_The_Pump_Started_In_The_Automatic_Mode_By_A_Pressure_Drop,
		form.Were_The_Pump_Bearings_Lubricated,
		form.Jockey_Pump_Start_Pressure_PSI,
		form.Jockey_Pump_Start_Pressure,
		form.Jockey_Pump_Stop_Pressure_PSI,
		form.Jockey_Pump_Stop_Pressure,
		form.Fire_Pump_Start_Pressure_PSI,
		form.Fire_Pump_Start_Pressure,
		form.Fire_Pump_Stop_Pressure_PSI,
		form.Fire_Pump_Stop_Pressure,
		form.Is_The_Fuel_Tank_At_Least_2_3_Full,
		form.Is_Engine_Oil_At_Correct_Level,
		form.Is_Engine_Coolant_At_Correct_Level,
		form.Is_The_Engine_Block_Heater_Working,
		form.Is_Pump_Room_Ventilation_Operating_Properly,
		form.Was_Water_Discharge_Observed_From_Heat_Exchanger_Return_Line,
		form.Was_Cooling_Line_Strainer_Cleaned_After_Test,
		form.Was_Pump_Run_For_At_Least_30_Minutes,
		form.Does_The_Switch_In_Auto_Alarm_Work,
		form.Does_The_Pump_Running_Alarm_Work,
		form.Does_The_Common_Alarm_Work,
		form.Was_Casing_Relief_Valve_Operating_Properly,
		form.Was_Pump_Run_For_At_Least_10_Minutes,
		form.Does_The_Loss_Of_Power_Alarm_Work,
		form.Does_The_Electric_Pump_Running_Alarm_Work,
		form.Power_Failure_Condition_Simulated_While_Pump_Operating_At_Peak_Load,
		form.Trasfer_Of_Power_To_Alternative_Power_Source_Verified,
		form.Power_Faulure_Condition_Removed,
		form.Pump_Reconnected_To_Normal_Power_Source_After_A_Time_Delay,
		form.Have_Anti_Freeze_Systems_Been_Tested,
		form.Freeze_Protection_In_Degrees_F,
		form.Are_Alarm_Valves_Water_Flow_Devices_And_Retards_In_Satisfactory_Condition,
		form.Water_Flow_Alarm_Test_Conducted_With_Inspectors_Test,
		form.Water_Flow_Alarm_Test_Conducted_With_Bypass_Connection,
		form.Is_Dry_Valve_In_Service_And_In_Good_Condition,
		form.Is_Dry_Valve_Itermediate_Chamber_Not_Leaking,
		form.Has_The_Dry_System_Been_Fully_Tripped_Within_The_Last_Three_Years,
		form.Are_Quick_Opening_Device_Control_Valves_Open,
		form.Is_There_A_List_Of_Known_Low_Point_Drains_At_The_Riser,
		form.Have_Known_Low_Points_Been_Drained,
		form.Is_Oil_Level_Full_On_Air_Compressor,
		form.Does_The_Air_Compressor_Return_System_Pressure_In_30_minutes_or_Under,
		form.What_Pressure_Does_Air_Compressor_Start_PSI,
		form.What_Pressure_Does_Air_Compressor_Start,
		form.What_Pressure_Does_Air_Compressor_Stop_PSI,
		form.What_Pressure_Does_Air_Compressor_Stop,
		form.Did_Low_Air_Alarm_Operate_PSI,
		form.Did_Low_Air_Alarm_Operate,
		ParseDate(form.Date_Of_Last_Full_Trip_Test),
		ParseDate(form.Date_Of_Last_Internal_Inspection),
		form.Are_Valves_In_Service_And_In_Good_Condition,
		form.Were_Valves_Tripped,
		form.What_Pressure_Did_Pneumatic_Actuator_Trip_PSI,
		form.What_Pressure_Did_Pneumatic_Actuator_Trip,
		form.Was_Priming_Line_Left_On_After_Test,
		form.What_Pressure_Does_Preaction_Air_Compressor_Start_PSI,
		form.What_Pressure_Does_Preaction_Air_Compressor_Start,
		form.What_Pressure_Does_Preaction_Air_Compressor_Stop_PSI,
		form.What_Pressure_Does_Preaction_Air_Compressor_Stop,
		form.Did_Preaction_Low_Air_Alarm_Operate_PSI,
		form.Did_Preaction_Low_Air_Alarm_Operate,
		form.Does_Water_Motor_Gong_Work,
		form.Does_Electric_Bell_Work,
		form.Are_Water_Flow_Alarms_Operational,
		form.Are_All_Tamper_Switches_Operational,
		form.Did_Alarm_Panel_Clear_After_Test,
		form.Are_A_Minimum_Of_6_Spare_Sprinklers_Readily_Avaiable,
		form.Is_Condition_Of_Piping_And_Other_System_Componets_Satisfactory,
		form.Are_Known_Dry_Type_Heads_Less_Than_10_Years_Old,
		form.Are_Known_Dry_Type_Heads_Less_Than_10_Years_Old_Year,
		form.Are_Known_Quick_Response_Heads_Less_Than_20_Years_Old,
		form.Are_Known_Quick_Response_Heads_Less_Than_20_Years_Old_Year,
		form.Are_Known_Standard_Response_Heads_Less_Than_50_Years_Old,
		form.Are_Known_Standard_Response_Heads_Less_Than_50_Years_Old_Year,
		form.Have_All_Gauges_Been_Tested_Or_Replaced_In_The_Last_5_Years,
		form.Have_All_Gauges_Been_Tested_Or_Replaced_In_The_Last_5_Years_Year,
		form.System_1_Name,
		form.System_1_Drain_Size,
		form.System_1_Static_PSI,
		form.System_1_Residual_PSI,
		form.System_2_Name,
		form.System_2_Drain_Size,
		form.System_2_Static_PSI,
		form.System_2_Residual_PSI,
		form.System_3_Name,
		form.System_3_Drain_Size,
		form.System_3_Static_PSI,
		form.System_3_Residual_PSI,
		form.System_4_Name,
		form.System_4_Drain_Size,
		form.System_4_Static_PSI,
		form.System_4_Residual_PSI,
		form.System_5_Name,
		form.System_5_Drain_Size,
		form.System_5_Static_PSI,
		form.System_5_Residual_PSI,
		form.System_6_Name,
		form.System_6_Drain_Size,
		form.System_6_Static_PSI,
		form.System_6_Residual_PSI,
		form.Drain_Test_Notes,
		form.Device_1_Name,
		form.Device_1_Address,
		form.Device_1_Description_Location,
		form.Device_1_Operated,
		form.Device_1_Delay_Sec,
		form.Device_2_Name,
		form.Device_2_Address,
		form.Device_2_Description_Location,
		form.Device_2_Operated,
		form.Device_2_Delay_Sec,
		form.Device_3_Name,
		form.Device_3_Address,
		form.Device_3_Description_Location,
		form.Device_3_Operated,
		form.Device_3_Delay_Sec,
		form.Device_4_Name,
		form.Device_4_Address,
		form.Device_4_Description_Location,
		form.Device_4_Operated,
		form.Device_4_Delay_Sec,
		form.Device_5_Name,
		form.Device_5_Address,
		form.Device_5_Description_Location,
		form.Device_5_Operated,
		form.Device_5_Delay_Sec,
		form.Device_6_Name,
		form.Device_6_Address,
		form.Device_6_Description_Location,
		form.Device_6_Operated,
		form.Device_6_Delay_Sec,
		form.Device_7_Name,
		form.Device_7_Address,
		form.Device_7_Description_Location,
		form.Device_7_Operated,
		form.Device_7_Delay_Sec,
		form.Device_8_Name,
		form.Device_8_Address,
		form.Device_8_Description_Location,
		form.Device_8_Operated,
		form.Device_8_Delay_Sec,
		form.Device_9_Name,
		form.Device_9_Address,
		form.Device_9_Description_Location,
		form.Device_9_Operated,
		form.Device_9_Delay_Sec,
		form.Device_10_Name,
		form.Device_10_Address,
		form.Device_10_Description_Location,
		form.Device_10_Operated,
		form.Device_10_Delay_Sec,
		form.Device_11_Name,
		form.Device_11_Address,
		form.Device_11_Description_Location,
		form.Device_11_Operated,
		form.Device_11_Delay_Sec,
		form.Device_12_Name,
		form.Device_12_Address,
		form.Device_12_Description_Location,
		form.Device_12_Operated,
		form.Device_12_Delay_Sec,
		form.Device_13_Name,
		form.Device_13_Address,
		form.Device_13_Description_Location,
		form.Device_13_Operated,
		form.Device_13_Delay_Sec,
		form.Device_14_Name,
		form.Device_14_Address,
		form.Device_14_Description_Location,
		form.Device_14_Operated,
		form.Device_14_Delay_Sec,
		form.Adjustments_Or_Corrections_Make,
		form.Explanation_Of_Any_No_Answers,
		form.Explanation_Of_Any_No_Answers_Continued,
		form.Notes,
	)
	if err != nil {
		utils.LogSafe("Could not insert into Inspection Table: %+v", err)
	}
}

func CreateDryTable(db *sql.DB) {
	query := `
	CREATE TABLE IF NOT EXISTS dry (
	id SERIAL PRIMARY KEY,
	pdf_path TEXT UNIQUE,
	report_to TEXT,
	building TEXT,
	report_to_2 TEXT,
	building_2 TEXT,
	attention TEXT,
	street TEXT,
	inspector TEXT,
	city_state TEXT,
	date DATE,
	dry_pipe_valve_make TEXT,
	dry_pipe_valve_model TEXT,
	dry_pipe_valve_size TEXT,
	dry_pipe_valve_year TEXT,
	dry_pipe_valve_controls_sprinklers_in TEXT,
	quick_opening_device_make TEXT,
	quick_opening_device_model TEXT,
	quick_opening_device_control_valve_open TEXT,
	quick_opening_device_year TEXT,
	trip_test_air_pressure_before_test TEXT,
	trip_test_air_system_tripped_at TEXT,
	trip_test_water_pressure_before_test TEXT,
	trip_test_time TEXT,
	trip_test_air_quick_opening_device_operated_at TEXT,
	trip_test_time_quick_opening_device_operated_at TEXT,
	trip_test_time_water_at_inspectors_test TEXT,
	trip_test_static_water_pressure TEXT,
	trip_test_residual_water_pressure TEXT,
	remarks_on_test TEXT
	)`
	_, err := db.Exec(query)
	if err != nil {
		utils.LogSafe("Could not create the Dry Table: %+v", err)
	}
}

func InsertDryTable(db *sql.DB, form models.DryForm) {
	query := `
	INSERT INTO dry (
	pdf_path,
	report_to,
	building,
	report_to_2,
	building_2,
	attention,
	street,
	inspector,
	city_state,
	date,
	dry_pipe_valve_make,
	dry_pipe_valve_model,
	dry_pipe_valve_size,
	dry_pipe_valve_year,
	dry_pipe_valve_controls_sprinklers_in,
	quick_opening_device_make,
	quick_opening_device_model,
	quick_opening_device_control_valve_open,
	quick_opening_device_year,
	trip_test_air_pressure_before_test,
	trip_test_air_system_tripped_at,
	trip_test_water_pressure_before_test,
	trip_test_time,
	trip_test_air_quick_opening_device_operated_at,
	trip_test_time_quick_opening_device_operated_at,
	trip_test_time_water_at_inspectors_test,
	trip_test_static_water_pressure,
	trip_test_residual_water_pressure,
	remarks_on_test
	) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9,
	$10,
	$11,
	$12,
	$13,
	$14,
	$15,
	$16,
	$17,
	$18,
	$19,
	$20,
	$21,
	$22,
	$23,
	$24,
	$25,
	$26,
	$27,
	$28,
	$29
	) ON CONFLICT (pdf_path) DO UPDATE SET
	report_to = EXCLUDED.report_to,
	building = EXCLUDED.building,
	report_to_2 = EXCLUDED.report_to_2,
	building_2 = EXCLUDED.building_2,
	attention = EXCLUDED.attention,
	street = EXCLUDED.street,
	inspector = EXCLUDED.inspector,
	city_state = EXCLUDED.city_state,
	date = EXCLUDED.date,
	dry_pipe_valve_make = EXCLUDED.dry_pipe_valve_make,
	dry_pipe_valve_model = EXCLUDED.dry_pipe_valve_model,
	dry_pipe_valve_size = EXCLUDED.dry_pipe_valve_size,
	dry_pipe_valve_year = EXCLUDED.dry_pipe_valve_year,
	dry_pipe_valve_controls_sprinklers_in = EXCLUDED.dry_pipe_valve_controls_sprinklers_in,
	quick_opening_device_make = EXCLUDED.quick_opening_device_make,
	quick_opening_device_model = EXCLUDED.quick_opening_device_model,
	quick_opening_device_control_valve_open = EXCLUDED.quick_opening_device_control_valve_open,
	quick_opening_device_year = EXCLUDED.quick_opening_device_year,
	trip_test_air_pressure_before_test = EXCLUDED.trip_test_air_pressure_before_test,
	trip_test_air_system_tripped_at = EXCLUDED.trip_test_air_system_tripped_at,
	trip_test_water_pressure_before_test = EXCLUDED.trip_test_water_pressure_before_test,
	trip_test_time = EXCLUDED.trip_test_time,
	trip_test_air_quick_opening_device_operated_at = EXCLUDED.trip_test_air_quick_opening_device_operated_at,
	trip_test_time_quick_opening_device_operated_at = EXCLUDED.trip_test_time_quick_opening_device_operated_at,
	trip_test_time_water_at_inspectors_test = EXCLUDED.trip_test_time_water_at_inspectors_test,
	trip_test_static_water_pressure = EXCLUDED.trip_test_static_water_pressure,
	trip_test_residual_water_pressure = EXCLUDED.trip_test_residual_water_pressure,
	remarks_on_test = EXCLUDED.remarks_on_test`
	_, err := db.Exec(query,
		form.PDF_Path,
		form.Report_To,
		form.Building,
		form.Report_To_2,
		form.Building_2,
		form.Attention,
		form.Street,
		form.Inspector,
		form.City_State,
		ParseDate(form.Date),
		form.Dry_Pipe_Valve_Make,
		form.Dry_Pipe_Valve_Model,
		form.Dry_Pipe_Valve_Size,
		form.Dry_Pipe_Valve_Year,
		form.Dry_Pipe_Valve_Controls_Sprinklers_In,
		form.Quick_Opening_Device_Make,
		form.Quick_Opening_Device_Model,
		form.Quick_Opening_Device_Control_Valve_Open,
		form.Quick_Opening_Device_Year,
		form.Trip_Test_Air_Pressure_Before_Test,
		form.Trip_Test_Air_System_Tripped_At,
		form.Trip_Test_Water_Pressure_Before_Test,
		form.Trip_Test_Time,
		form.Trip_Test_Air_Quick_Opening_Device_Operated_At,
		form.Trip_Test_Time_Quick_Opening_Device_Operated_At,
		form.Trip_Test_Time_Water_At_Inspectors_Test,
		form.Trip_Test_Static_Water_Pressure,
		form.Trip_Test_Residual_Water_Pressure,
		form.Remarks_On_Test,
	)
	if err != nil {
		utils.LogSafe("Could not insert into Dry Table: %+v", err)
	}
}

func CreatePumpTable(db *sql.DB) {
	query := `
	CREATE TABLE IF NOT EXISTS pump (
	id SERIAL PRIMARY KEY,
	pdf_path TEXT UNIQUE,
	report_to TEXT,
	building TEXT,
	attention TEXT,
	street TEXT,
	inspector TEXT,
	city_state TEXT,
	date DATE,
	pump_make TEXT,
	pump_rated_rpm TEXT,
	pump_model TEXT,
	pump_rated_gpm TEXT,
	pump_serial_number TEXT,
	pump_max_psi TEXT,
	pump_power TEXT,
	pump_rated_psi TEXT,
	pump_water_supply TEXT,
	pump_psi_at_150_percent TEXT,
	pump_controller_make TEXT,
	pump_controller_voltage TEXT,
	pump_controller_model TEXT,
	pump_controller_horse_power TEXT,
	pump_controller_serial_number TEXT,
	pump_controller_supervision TEXT,
	diesel_engine_make TEXT,
	diesel_engine_serial_number TEXT,
	diesel_engine_model TEXT,
	diesel_engine_hours TEXT,
	flow_test_orifice_size_1 TEXT,
	flow_test_orifice_size_2 TEXT,
	flow_test_orifice_size_3 TEXT,
	flow_test_orifice_size_4 TEXT,
	flow_test_orifice_size_5 TEXT,
	flow_test_orifice_size_6 TEXT,
	flow_test_orifice_size_7 TEXT,
	flow_test_1_suction_psi TEXT,
	flow_test_1_discharge_psi TEXT,
	flow_test_1_net_psi TEXT,
	flow_test_1_rpm TEXT,
	flow_test_1_o1_pitot TEXT,
	flow_test_1_o2_pitot TEXT,
	flow_test_1_o3_pitot TEXT,
	flow_test_1_o4_pitot TEXT,
	flow_test_1_o5_pitot TEXT,
	flow_test_1_o6_pitot TEXT,
	flow_test_1_o7_pitot TEXT,
	flow_test_1_o1_gpm TEXT,
	flow_test_1_o2_gpm TEXT,
	flow_test_1_o3_gpm TEXT,
	flow_test_1_o4_gpm TEXT,
	flow_test_1_o5_gpm TEXT,
	flow_test_1_o6_gpm TEXT,
	flow_test_1_o7_gpm TEXT,
	flow_test_1_total_flow TEXT,
	flow_test_2_suction_psi TEXT,
	flow_test_2_discharge_psi TEXT,
	flow_test_2_net_psi TEXT,
	flow_test_2_rpm TEXT,
	flow_test_2_o1_pitot TEXT,
	flow_test_2_o2_pitot TEXT,
	flow_test_2_o3_pitot TEXT,
	flow_test_2_o4_pitot TEXT,
	flow_test_2_o5_pitot TEXT,
	flow_test_2_o6_pitot TEXT,
	flow_test_2_o7_pitot TEXT,
	flow_test_2_o1_gpm TEXT,
	flow_test_2_o2_gpm TEXT,
	flow_test_2_o3_gpm TEXT,
	flow_test_2_o4_gpm TEXT,
	flow_test_2_o5_gpm TEXT,
	flow_test_2_o6_gpm TEXT,
	flow_test_2_o7_gpm TEXT,
	flow_test_2_total_flow TEXT,
	flow_test_3_suction_psi TEXT,
	flow_test_3_discharge_psi TEXT,
	flow_test_3_net_psi TEXT,
	flow_test_3_rpm TEXT,
	flow_test_3_o1_pitot TEXT,
	flow_test_3_o2_pitot TEXT,
	flow_test_3_o3_pitot TEXT,
	flow_test_3_o4_pitot TEXT,
	flow_test_3_o5_pitot TEXT,
	flow_test_3_o6_pitot TEXT,
	flow_test_3_o7_pitot TEXT,
	flow_test_3_o1_gpm TEXT,
	flow_test_3_o2_gpm TEXT,
	flow_test_3_o3_gpm TEXT,
	flow_test_3_o4_gpm TEXT,
	flow_test_3_o5_gpm TEXT,
	flow_test_3_o6_gpm TEXT,
	flow_test_3_o7_gpm TEXT,
	flow_test_3_total_flow TEXT,
	flow_test_4_suction_psi TEXT,
	flow_test_4_discharge_psi TEXT,
	flow_test_4_net_psi TEXT,
	flow_test_4_rpm TEXT,
	flow_test_4_o1_pitot TEXT,
	flow_test_4_o2_pitot TEXT,
	flow_test_4_o3_pitot TEXT,
	flow_test_4_o4_pitot TEXT,
	flow_test_4_o5_pitot TEXT,
	flow_test_4_o6_pitot TEXT,
	flow_test_4_o7_pitot TEXT,
	flow_test_4_o1_gpm TEXT,
	flow_test_4_o2_gpm TEXT,
	flow_test_4_o3_gpm TEXT,
	flow_test_4_o4_gpm TEXT,
	flow_test_4_o5_gpm TEXT,
	flow_test_4_o6_gpm TEXT,
	flow_test_4_o7_gpm TEXT,
	flow_test_4_total_flow TEXT,
	remarks_on_test TEXT
	)`
	_, err := db.Exec(query)
	if err != nil {
		utils.LogSafe("Could not create the Pump Table: %+v", err)
	}
}

func InsertPumpTable(db *sql.DB, form models.PumpForm) {
	query := `
	INSERT INTO pump (
	pdf_path,
	report_to,
	building,
	attention,
	street,
	inspector,
	city_state,
	date,
	pump_make,
	pump_rated_rpm,
	pump_model,
	pump_rated_gpm,
	pump_serial_number,
	pump_max_psi,
	pump_power,
	pump_rated_psi,
	pump_water_supply,
	pump_psi_at_150_percent,
	pump_controller_make,
	pump_controller_voltage,
	pump_controller_model,
	pump_controller_horse_power,
	pump_controller_serial_number,
	pump_controller_supervision,
	diesel_engine_make,
	diesel_engine_serial_number,
	diesel_engine_model,
	diesel_engine_hours,
	flow_test_orifice_size_1,
	flow_test_orifice_size_2,
	flow_test_orifice_size_3,
	flow_test_orifice_size_4,
	flow_test_orifice_size_5,
	flow_test_orifice_size_6,
	flow_test_orifice_size_7,
	flow_test_1_suction_psi,
	flow_test_1_discharge_psi,
	flow_test_1_net_psi,
	flow_test_1_rpm,
	flow_test_1_o1_pitot,
	flow_test_1_o2_pitot,
	flow_test_1_o3_pitot,
	flow_test_1_o4_pitot,
	flow_test_1_o5_pitot,
	flow_test_1_o6_pitot,
	flow_test_1_o7_pitot,
	flow_test_1_o1_gpm,
	flow_test_1_o2_gpm,
	flow_test_1_o3_gpm,
	flow_test_1_o4_gpm,
	flow_test_1_o5_gpm,
	flow_test_1_o6_gpm,
	flow_test_1_o7_gpm,
	flow_test_1_total_flow,
	flow_test_2_suction_psi,
	flow_test_2_discharge_psi,
	flow_test_2_net_psi,
	flow_test_2_rpm,
	flow_test_2_o1_pitot,
	flow_test_2_o2_pitot,
	flow_test_2_o3_pitot,
	flow_test_2_o4_pitot,
	flow_test_2_o5_pitot,
	flow_test_2_o6_pitot,
	flow_test_2_o7_pitot,
	flow_test_2_o1_gpm,
	flow_test_2_o2_gpm,
	flow_test_2_o3_gpm,
	flow_test_2_o4_gpm,
	flow_test_2_o5_gpm,
	flow_test_2_o6_gpm,
	flow_test_2_o7_gpm,
	flow_test_2_total_flow,
	flow_test_3_suction_psi,
	flow_test_3_discharge_psi,
	flow_test_3_net_psi,
	flow_test_3_rpm,
	flow_test_3_o1_pitot,
	flow_test_3_o2_pitot,
	flow_test_3_o3_pitot,
	flow_test_3_o4_pitot,
	flow_test_3_o5_pitot,
	flow_test_3_o6_pitot,
	flow_test_3_o7_pitot,
	flow_test_3_o1_gpm,
	flow_test_3_o2_gpm,
	flow_test_3_o3_gpm,
	flow_test_3_o4_gpm,
	flow_test_3_o5_gpm,
	flow_test_3_o6_gpm,
	flow_test_3_o7_gpm,
	flow_test_3_total_flow,
	flow_test_4_suction_psi,
	flow_test_4_discharge_psi,
	flow_test_4_net_psi,
	flow_test_4_rpm,
	flow_test_4_o1_pitot,
	flow_test_4_o2_pitot,
	flow_test_4_o3_pitot,
	flow_test_4_o4_pitot,
	flow_test_4_o5_pitot,
	flow_test_4_o6_pitot,
	flow_test_4_o7_pitot,
	flow_test_4_o1_gpm,
	flow_test_4_o2_gpm,
	flow_test_4_o3_gpm,
	flow_test_4_o4_gpm,
	flow_test_4_o5_gpm,
	flow_test_4_o6_gpm,
	flow_test_4_o7_gpm,
	flow_test_4_total_flow,
	remarks_on_test
	) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9,
	$10,
	$11,
	$12,
	$13,
	$14,
	$15,
	$16,
	$17,
	$18,
	$19,
	$20,
	$21,
	$22,
	$23,
	$24,
	$25,
	$26,
	$27,
	$28,
	$29,
	$30,
	$31,
	$32,
	$33,
	$34,
	$35,
	$36,
	$37,
	$38,
	$39,
	$40,
	$41,
	$42,
	$43,
	$44,
	$45,
	$46,
	$47,
	$48,
	$49,
	$50,
	$51,
	$52,
	$53,
	$54,
	$55,
	$56,
	$57,
	$58,
	$59,
	$60,
	$61,
	$62,
	$63,
	$64,
	$65,
	$66,
	$67,
	$68,
	$69,
	$70,
	$71,
	$72,
	$73,
	$74,
	$75,
	$76,
	$77,
	$78,
	$79,
	$80,
	$81,
	$82,
	$83,
	$84,
	$85,
	$86,
	$87,
	$88,
	$89,
	$90,
	$91,
	$92,
	$93,
	$94,
	$95,
	$96,
	$97,
	$98,
	$99,
	$100,
	$101,
	$102,
	$103,
	$104,
	$105,
	$106,
	$107,
	$108,
	$109,
	$110,
	$111,
	$112
	) ON CONFLICT (pdf_path) DO UPDATE SET
	report_to = EXCLUDED.report_to,
	building = EXCLUDED.building,
	attention = EXCLUDED.attention,
	street = EXCLUDED.street,
	inspector = EXCLUDED.inspector,
	city_state = EXCLUDED.city_state,
	date = EXCLUDED.date,
	pump_make = EXCLUDED.pump_make,
	pump_rated_rpm = EXCLUDED.pump_rated_rpm,
	pump_model = EXCLUDED.pump_model,
	pump_rated_gpm = EXCLUDED.pump_rated_gpm,
	pump_serial_number = EXCLUDED.pump_serial_number,
	pump_max_psi = EXCLUDED.pump_max_psi,
	pump_power = EXCLUDED.pump_power,
	pump_rated_psi = EXCLUDED.pump_rated_psi,
	pump_water_supply = EXCLUDED.pump_water_supply,
	pump_psi_at_150_percent = EXCLUDED.pump_psi_at_150_percent,
	pump_controller_make = EXCLUDED.pump_controller_make,
	pump_controller_voltage = EXCLUDED.pump_controller_voltage,
	pump_controller_model = EXCLUDED.pump_controller_model,
	pump_controller_horse_power = EXCLUDED.pump_controller_horse_power,
	pump_controller_serial_number = EXCLUDED.pump_controller_serial_number,
	pump_controller_supervision = EXCLUDED.pump_controller_supervision,
	diesel_engine_make = EXCLUDED.diesel_engine_make,
	diesel_engine_serial_number = EXCLUDED.diesel_engine_serial_number,
	diesel_engine_model = EXCLUDED.diesel_engine_model,
	diesel_engine_hours = EXCLUDED.diesel_engine_hours,
	flow_test_orifice_size_1 = EXCLUDED.flow_test_orifice_size_1,
	flow_test_orifice_size_2 = EXCLUDED.flow_test_orifice_size_2,
	flow_test_orifice_size_3 = EXCLUDED.flow_test_orifice_size_3,
	flow_test_orifice_size_4 = EXCLUDED.flow_test_orifice_size_4,
	flow_test_orifice_size_5 = EXCLUDED.flow_test_orifice_size_5,
	flow_test_orifice_size_6 = EXCLUDED.flow_test_orifice_size_6,
	flow_test_orifice_size_7 = EXCLUDED.flow_test_orifice_size_7,
	flow_test_1_suction_psi = EXCLUDED.flow_test_1_suction_psi,
	flow_test_1_discharge_psi = EXCLUDED.flow_test_1_discharge_psi,
	flow_test_1_net_psi = EXCLUDED.flow_test_1_net_psi,
	flow_test_1_rpm = EXCLUDED.flow_test_1_rpm,
	flow_test_1_o1_pitot = EXCLUDED.flow_test_1_o1_pitot,
	flow_test_1_o2_pitot = EXCLUDED.flow_test_1_o2_pitot,
	flow_test_1_o3_pitot = EXCLUDED.flow_test_1_o3_pitot,
	flow_test_1_o4_pitot = EXCLUDED.flow_test_1_o4_pitot,
	flow_test_1_o5_pitot = EXCLUDED.flow_test_1_o5_pitot,
	flow_test_1_o6_pitot = EXCLUDED.flow_test_1_o6_pitot,
	flow_test_1_o7_pitot = EXCLUDED.flow_test_1_o7_pitot,
	flow_test_1_o1_gpm = EXCLUDED.flow_test_1_o1_gpm,
	flow_test_1_o2_gpm = EXCLUDED.flow_test_1_o2_gpm,
	flow_test_1_o3_gpm = EXCLUDED.flow_test_1_o3_gpm,
	flow_test_1_o4_gpm = EXCLUDED.flow_test_1_o4_gpm,
	flow_test_1_o5_gpm = EXCLUDED.flow_test_1_o5_gpm,
	flow_test_1_o6_gpm = EXCLUDED.flow_test_1_o6_gpm,
	flow_test_1_o7_gpm = EXCLUDED.flow_test_1_o7_gpm,
	flow_test_1_total_flow = EXCLUDED.flow_test_1_total_flow,
	flow_test_2_suction_psi = EXCLUDED.flow_test_2_suction_psi,
	flow_test_2_discharge_psi = EXCLUDED.flow_test_2_discharge_psi,
	flow_test_2_net_psi = EXCLUDED.flow_test_2_net_psi,
	flow_test_2_rpm = EXCLUDED.flow_test_2_rpm,
	flow_test_2_o1_pitot = EXCLUDED.flow_test_2_o1_pitot,
	flow_test_2_o2_pitot = EXCLUDED.flow_test_2_o2_pitot,
	flow_test_2_o3_pitot = EXCLUDED.flow_test_2_o3_pitot,
	flow_test_2_o4_pitot = EXCLUDED.flow_test_2_o4_pitot,
	flow_test_2_o5_pitot = EXCLUDED.flow_test_2_o5_pitot,
	flow_test_2_o6_pitot = EXCLUDED.flow_test_2_o6_pitot,
	flow_test_2_o7_pitot = EXCLUDED.flow_test_2_o7_pitot,
	flow_test_2_o1_gpm = EXCLUDED.flow_test_2_o1_gpm,
	flow_test_2_o2_gpm = EXCLUDED.flow_test_2_o2_gpm,
	flow_test_2_o3_gpm = EXCLUDED.flow_test_2_o3_gpm,
	flow_test_2_o4_gpm = EXCLUDED.flow_test_2_o4_gpm,
	flow_test_2_o5_gpm = EXCLUDED.flow_test_2_o5_gpm,
	flow_test_2_o6_gpm = EXCLUDED.flow_test_2_o6_gpm,
	flow_test_2_o7_gpm = EXCLUDED.flow_test_2_o7_gpm,
	flow_test_2_total_flow = EXCLUDED.flow_test_2_total_flow,
	flow_test_3_suction_psi = EXCLUDED.flow_test_3_suction_psi,
	flow_test_3_discharge_psi = EXCLUDED.flow_test_3_discharge_psi,
	flow_test_3_net_psi = EXCLUDED.flow_test_3_net_psi,
	flow_test_3_rpm = EXCLUDED.flow_test_3_rpm,
	flow_test_3_o1_pitot = EXCLUDED.flow_test_3_o1_pitot,
	flow_test_3_o2_pitot = EXCLUDED.flow_test_3_o2_pitot,
	flow_test_3_o3_pitot = EXCLUDED.flow_test_3_o3_pitot,
	flow_test_3_o4_pitot = EXCLUDED.flow_test_3_o4_pitot,
	flow_test_3_o5_pitot = EXCLUDED.flow_test_3_o5_pitot,
	flow_test_3_o6_pitot = EXCLUDED.flow_test_3_o6_pitot,
	flow_test_3_o7_pitot = EXCLUDED.flow_test_3_o7_pitot,
	flow_test_3_o1_gpm = EXCLUDED.flow_test_3_o1_gpm,
	flow_test_3_o2_gpm = EXCLUDED.flow_test_3_o2_gpm,
	flow_test_3_o3_gpm = EXCLUDED.flow_test_3_o3_gpm,
	flow_test_3_o4_gpm = EXCLUDED.flow_test_3_o4_gpm,
	flow_test_3_o5_gpm = EXCLUDED.flow_test_3_o5_gpm,
	flow_test_3_o6_gpm = EXCLUDED.flow_test_3_o6_gpm,
	flow_test_3_o7_gpm = EXCLUDED.flow_test_3_o7_gpm,
	flow_test_3_total_flow = EXCLUDED.flow_test_3_total_flow,
	flow_test_4_suction_psi = EXCLUDED.flow_test_4_suction_psi,
	flow_test_4_discharge_psi = EXCLUDED.flow_test_4_discharge_psi,
	flow_test_4_net_psi = EXCLUDED.flow_test_4_net_psi,
	flow_test_4_rpm = EXCLUDED.flow_test_4_rpm,
	flow_test_4_o1_pitot = EXCLUDED.flow_test_4_o1_pitot,
	flow_test_4_o2_pitot = EXCLUDED.flow_test_4_o2_pitot,
	flow_test_4_o3_pitot = EXCLUDED.flow_test_4_o3_pitot,
	flow_test_4_o4_pitot = EXCLUDED.flow_test_4_o4_pitot,
	flow_test_4_o5_pitot = EXCLUDED.flow_test_4_o5_pitot,
	flow_test_4_o6_pitot = EXCLUDED.flow_test_4_o6_pitot,
	flow_test_4_o7_pitot = EXCLUDED.flow_test_4_o7_pitot,
	flow_test_4_o1_gpm = EXCLUDED.flow_test_4_o1_gpm,
	flow_test_4_o2_gpm = EXCLUDED.flow_test_4_o2_gpm,
	flow_test_4_o3_gpm = EXCLUDED.flow_test_4_o3_gpm,
	flow_test_4_o4_gpm = EXCLUDED.flow_test_4_o4_gpm,
	flow_test_4_o5_gpm = EXCLUDED.flow_test_4_o5_gpm,
	flow_test_4_o6_gpm = EXCLUDED.flow_test_4_o6_gpm,
	flow_test_4_o7_gpm = EXCLUDED.flow_test_4_o7_gpm,
	flow_test_4_total_flow = EXCLUDED.flow_test_4_total_flow,
	remarks_on_test = EXCLUDED.remarks_on_test`
	_, err := db.Exec(query,
		form.PDF_Path,
		form.Report_To,
		form.Building,
		form.Attention,
		form.Street,
		form.Inspector,
		form.City_State,
		ParseDate(form.Date),
		form.Pump_Make,
		form.Pump_Rated_RPM,
		form.Pump_Model,
		form.Pump_Rated_GPM,
		form.Pump_Serial_Number,
		form.Pump_Max_PSI,
		form.Pump_Power,
		form.Pump_Rated_PSI,
		form.Pump_Water_Supply,
		form.Pump_PSI_At_150_Percent,
		form.Pump_Controller_Make,
		form.Pump_Controller_Voltage,
		form.Pump_Controller_Model,
		form.Pump_Controller_Horse_Power,
		form.Pump_Controller_Serial_Number,
		form.Pump_Controller_Supervision,
		form.Diesel_Engine_Make,
		form.Diesel_Engine_Serial_Number,
		form.Diesel_Engine_Model,
		form.Diesel_Engine_Hours,
		form.Flow_Test_Orifice_Size_1,
		form.Flow_Test_Orifice_Size_2,
		form.Flow_Test_Orifice_Size_3,
		form.Flow_Test_Orifice_Size_4,
		form.Flow_Test_Orifice_Size_5,
		form.Flow_Test_Orifice_Size_6,
		form.Flow_Test_Orifice_Size_7,
		form.Flow_Test_1_Suction_PSI,
		form.Flow_Test_1_Discharge_PSI,
		form.Flow_Test_1_Net_PSI,
		form.Flow_Test_1_RPM,
		form.Flow_Test_1_O1_Pitot,
		form.Flow_Test_1_O2_Pitot,
		form.Flow_Test_1_O3_Pitot,
		form.Flow_Test_1_O4_Pitot,
		form.Flow_Test_1_O5_Pitot,
		form.Flow_Test_1_O6_Pitot,
		form.Flow_Test_1_O7_Pitot,
		form.Flow_Test_1_O1_GPM,
		form.Flow_Test_1_O2_GPM,
		form.Flow_Test_1_O3_GPM,
		form.Flow_Test_1_O4_GPM,
		form.Flow_Test_1_O5_GPM,
		form.Flow_Test_1_O6_GPM,
		form.Flow_Test_1_O7_GPM,
		form.Flow_Test_1_Total_Flow,
		form.Flow_Test_2_Suction_PSI,
		form.Flow_Test_2_Discharge_PSI,
		form.Flow_Test_2_Net_PSI,
		form.Flow_Test_2_RPM,
		form.Flow_Test_2_O1_Pitot,
		form.Flow_Test_2_O2_Pitot,
		form.Flow_Test_2_O3_Pitot,
		form.Flow_Test_2_O4_Pitot,
		form.Flow_Test_2_O5_Pitot,
		form.Flow_Test_2_O6_Pitot,
		form.Flow_Test_2_O7_Pitot,
		form.Flow_Test_2_O1_GPM,
		form.Flow_Test_2_O2_GPM,
		form.Flow_Test_2_O3_GPM,
		form.Flow_Test_2_O4_GPM,
		form.Flow_Test_2_O5_GPM,
		form.Flow_Test_2_O6_GPM,
		form.Flow_Test_2_O7_GPM,
		form.Flow_Test_2_Total_Flow,
		form.Flow_Test_3_Suction_PSI,
		form.Flow_Test_3_Discharge_PSI,
		form.Flow_Test_3_Net_PSI,
		form.Flow_Test_3_RPM,
		form.Flow_Test_3_O1_Pitot,
		form.Flow_Test_3_O2_Pitot,
		form.Flow_Test_3_O3_Pitot,
		form.Flow_Test_3_O4_Pitot,
		form.Flow_Test_3_O5_Pitot,
		form.Flow_Test_3_O6_Pitot,
		form.Flow_Test_3_O7_Pitot,
		form.Flow_Test_3_O1_GPM,
		form.Flow_Test_3_O2_GPM,
		form.Flow_Test_3_O3_GPM,
		form.Flow_Test_3_O4_GPM,
		form.Flow_Test_3_O5_GPM,
		form.Flow_Test_3_O6_GPM,
		form.Flow_Test_3_O7_GPM,
		form.Flow_Test_3_Total_Flow,
		form.Flow_Test_4_Suction_PSI,
		form.Flow_Test_4_Discharge_PSI,
		form.Flow_Test_4_Net_PSI,
		form.Flow_Test_4_RPM,
		form.Flow_Test_4_O1_Pitot,
		form.Flow_Test_4_O2_Pitot,
		form.Flow_Test_4_O3_Pitot,
		form.Flow_Test_4_O4_Pitot,
		form.Flow_Test_4_O5_Pitot,
		form.Flow_Test_4_O6_Pitot,
		form.Flow_Test_4_O7_Pitot,
		form.Flow_Test_4_O1_GPM,
		form.Flow_Test_4_O2_GPM,
		form.Flow_Test_4_O3_GPM,
		form.Flow_Test_4_O4_GPM,
		form.Flow_Test_4_O5_GPM,
		form.Flow_Test_4_O6_GPM,
		form.Flow_Test_4_O7_GPM,
		form.Flow_Test_4_Total_Flow,
		form.Remarks_On_Test,
	)
	if err != nil {
		utils.LogSafe("Could not insert into Dry Table: %+v", err)
	}
}

func CreateBackflowTable(db *sql.DB) {
	query := `
	CREATE TABLE IF NOT EXISTS backflow (
	id SERIAL PRIMARY KEY,
	pdf_path TEXT UNIQUE,
	owner_of_property TEXT,
	date DATE,
	mailing_address TEXT,
	tested_by TEXT,
	certificate_number TEXT,
	contact_person TEXT,
	backflow_type TEXT,
	backflow_make TEXT,
	backflow_model TEXT,
	backflow_size TEXT,
	backflow_serial_number TEXT,
	test_type TEXT,
	device_location TEXT,
	rpz_check_valve_1_closed_tight TEXT,
	rpz_check_valve_1_leaked TEXT,
	rpz_check_valve_1_psid TEXT,
	rpz_check_valve_2_closed_tight TEXT,
	rpz_check_valve_flow TEXT,
	rpz_check_valve_no_flow TEXT,
	pvb_srvb_check_valve_flow TEXT,
	rpz_relief_valve_opened_at_psid TEXT,
	rpz_check_valve_2_psid TEXT,
	rpz_check_valve_2_leaked TEXT,
	pvb_srvb_check_valve_psid TEXT,
	rpz_relief_valve_did_not_open TEXT,
	pvb_srvb_air_inlet_valve_opened_at_psid TEXT,
	dcva_back_pressure_test_1_psi TEXT,
	dcva_back_pressure_test_4_psi TEXT,
	dcva_check_valve_1_psid TEXT,
	dcva_check_valve_2_psid TEXT,
	dcva_flow TEXT,
	dcva_no_flow TEXT,
	downsteam_shutoff_valve_status TEXT,
	pvb_srvb_air_inlet_valve_did_not_open TEXT,
	protection_type TEXT,
	result TEXT,
	remarks_1 TEXT,
	remarks_2 TEXT,
	witness TEXT,
	remarks_3 TEXT
	)`
	_, err := db.Exec(query)
	if err != nil {
		utils.LogSafe("Could not create the Backflow Table: %+v", err)
	}
}

func InsertBackflowTable(db *sql.DB, form models.BackflowForm) {
	query := `
	INSERT INTO backflow (
	pdf_path,
	owner_of_property,
	date,
	mailing_address,
	tested_by,
	certificate_number,
	contact_person,
	backflow_type,
	backflow_make,
	backflow_model,
	backflow_size,
	backflow_serial_number,
	test_type,
	device_location,
	rpz_check_valve_1_closed_tight,
	rpz_check_valve_1_leaked,
	rpz_check_valve_1_psid,
	rpz_check_valve_2_closed_tight,
	rpz_check_valve_flow,
	rpz_check_valve_no_flow,
	pvb_srvb_check_valve_flow,
	rpz_relief_valve_opened_at_psid,
	rpz_check_valve_2_psid,
	rpz_check_valve_2_leaked,
	pvb_srvb_check_valve_psid,
	rpz_relief_valve_did_not_open,
	pvb_srvb_air_inlet_valve_opened_at_psid,
	dcva_back_pressure_test_1_psi,
	dcva_back_pressure_test_4_psi,
	dcva_check_valve_1_psid,
	dcva_check_valve_2_psid,
	dcva_flow,
	dcva_no_flow,
	downsteam_shutoff_valve_status,
	pvb_srvb_air_inlet_valve_did_not_open,
	protection_type,
	result,
	remarks_1,
	remarks_2,
	witness,
	remarks_3
	) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9,
	$10,
	$11,
	$12,
	$13,
	$14,
	$15,
	$16,
	$17,
	$18,
	$19,
	$20,
	$21,
	$22,
	$23,
	$24,
	$25,
	$26,
	$27,
	$28,
	$29,
	$30,
	$31,
	$32,
	$33,
	$34,
	$35,
	$36,
	$37,
	$38,
	$39,
	$40,
	$41
	)  ON CONFLICT (pdf_path) DO UPDATE SET
	owner_of_property = EXCLUDED.owner_of_property,
	date = EXCLUDED.date,
	mailing_address = EXCLUDED.mailing_address,
	tested_by = EXCLUDED.tested_by,
	certificate_number = EXCLUDED.certificate_number,
	contact_person = EXCLUDED.contact_person,
	backflow_type = EXCLUDED.backflow_type,
	backflow_make = EXCLUDED.backflow_make,
	backflow_model = EXCLUDED.backflow_model,
	backflow_size = EXCLUDED.backflow_size,
	backflow_serial_number = EXCLUDED.backflow_serial_number,
	test_type = EXCLUDED.test_type,
	device_location = EXCLUDED.device_location,
	rpz_check_valve_1_closed_tight = EXCLUDED.rpz_check_valve_1_closed_tight,
	rpz_check_valve_1_leaked = EXCLUDED.rpz_check_valve_1_leaked,
	rpz_check_valve_1_psid = EXCLUDED.rpz_check_valve_1_psid,
	rpz_check_valve_2_closed_tight = EXCLUDED.rpz_check_valve_2_closed_tight,
	rpz_check_valve_flow = EXCLUDED.rpz_check_valve_flow,
	rpz_check_valve_no_flow = EXCLUDED.rpz_check_valve_no_flow,
	pvb_srvb_check_valve_flow = EXCLUDED.pvb_srvb_check_valve_flow,
	rpz_relief_valve_opened_at_psid = EXCLUDED.rpz_relief_valve_opened_at_psid,
	rpz_check_valve_2_psid = EXCLUDED.rpz_check_valve_2_psid,
	rpz_check_valve_2_leaked = EXCLUDED.rpz_check_valve_2_leaked,
	pvb_srvb_check_valve_psid = EXCLUDED.pvb_srvb_check_valve_psid,
	rpz_relief_valve_did_not_open = EXCLUDED.rpz_relief_valve_did_not_open,
	pvb_srvb_air_inlet_valve_opened_at_psid = EXCLUDED.pvb_srvb_air_inlet_valve_opened_at_psid,
	dcva_back_pressure_test_1_psi = EXCLUDED.dcva_back_pressure_test_1_psi,
	dcva_back_pressure_test_4_psi = EXCLUDED.dcva_back_pressure_test_4_psi,
	dcva_check_valve_1_psid = EXCLUDED.dcva_check_valve_1_psid,
	dcva_check_valve_2_psid = EXCLUDED.dcva_check_valve_2_psid,
	dcva_flow = EXCLUDED.dcva_flow,
	dcva_no_flow = EXCLUDED.dcva_no_flow,
	downsteam_shutoff_valve_status = EXCLUDED.downsteam_shutoff_valve_status,
	pvb_srvb_air_inlet_valve_did_not_open = EXCLUDED.pvb_srvb_air_inlet_valve_did_not_open,
	protection_type = EXCLUDED.protection_type,
	result = EXCLUDED.result,
	remarks_1 = EXCLUDED.remarks_1,
	remarks_2 = EXCLUDED.remarks_2,
	witness = EXCLUDED.witness,
	remarks_3 = EXCLUDED.remarks_3
	`
	_, err := db.Exec(query,
		form.PDF_Path,
		form.Owner_Of_Property,
		ParseDate(form.Date),
		form.Mailing_Address,
		form.Tested_By,
		form.Certificate_Number,
		form.Contact_Person,
		form.Backflow_Type,
		form.Backflow_Make,
		form.Backflow_Model,
		form.Backflow_Size,
		form.Backflow_Serial_Number,
		form.Test_Type,
		form.Device_Location,
		form.RPZ_Check_Valve_1_Closed_Tight,
		form.RPZ_Check_Valve_1_Leaked,
		form.RPZ_Check_Valve_1_PSID,
		form.RPZ_Check_Valve_2_Closed_Tight,
		form.RPZ_Check_Valve_Flow,
		form.RPZ_Check_Valve_No_Flow,
		form.PVB_SRVB_Check_Valve_Flow,
		form.RPZ_Relief_Valve_Opened_At_PSID,
		form.RPZ_Check_Valve_2_PSID,
		form.RPZ_Check_Valve_2_Leaked,
		form.PVB_SRVB_Check_Valve_PSID,
		form.RPZ_Relief_Valve_Did_Not_Open,
		form.PVB_SRVB_Air_Inlet_Valve_Opened_At_PSID,
		form.DCVA_Back_Pressure_Test_1_PSI,
		form.DCVA_Back_Pressure_Test_4_PSI,
		form.DCVA_Check_Valve_1_PSID,
		form.DCVA_Check_Valve_2_PSID,
		form.DCVA_Flow,
		form.DCVA_No_Flow,
		form.Downsteam_Shutoff_Valve_Status,
		form.PVB_SRVB_Air_Inlet_Valve_Did_Not_Open,
		form.Protection_Type,
		form.Result,
		form.Remarks_1,
		form.Remarks_2,
		form.Witness,
		form.Remarks_3,
	)
	if err != nil {
		utils.LogSafe("Could not insert into Backflow Table: %+v", err)
	}
}
